In [17]:
import tensorflow as tf
# --- Crear tensores ---
t_zeros = tf.zeros((3, 4))
t_rand = tf.random.uniform((2, 3))
t_const = tf.constant([[1.0, 2.0], [3.0, 4.0]])
print("Shape:", t_rand.shape) # (2, 3)
print("dtype:", t_rand.dtype) # float32
# --- Operaciones ---
a = tf.constant([1.0, 2.0, 3.0])
b = tf.constant([4.0, 5.0, 6.0])
print(a + b) # tf.Tensor([5. 7. 9.], ...)
print(tf.tensordot(a, b, axes=1))
# --- GradientTape: equivalente al autograd de PyTorch ---
x = tf.Variable(2.0) # Variable = tensor entrenable
w = tf.Variable(3.0)
b_val = tf.Variable(1.0)
with tf.GradientTape() as tape:
    y = w * x + b_val
grads = tape.gradient(y, [x, w, b_val])
print("grad x:", grads[0].numpy()) # 3.0
print("grad w:", grads[1].numpy()) # 2.0
print("grad b:", grads[2].numpy()) # 1.0

Shape: (2, 3)
dtype: <dtype: 'float32'>
tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
tf.Tensor(32.0, shape=(), dtype=float32)
grad x: 3.0
grad w: 2.0
grad b: 1.0


In [18]:
import tensorflow as tf
# Una capa densa: 3 entradas → 1 salida
neurona = tf.keras.layers.Dense(units=1, input_shape=(3,))
# Forward pass
import numpy as np
x = np.random.rand(5, 3).astype(np.float32)
y_pred = neurona(x)
print("Salida:", y_pred.shape) # (5, 1)
print(y_pred.numpy())
# Ver parámetros
print("Pesos:", neurona.kernel.shape) # (3, 1)
print("Bias:", neurona.bias.shape) # (1,)

c:\Users\Tomas\Documents\GitHub\framework-ia-UDD\.venv_tensor\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Salida: (5, 1)
[[-0.09740562]
 [-0.11603521]
 [-0.4481364 ]
 [-0.05265117]
 [-0.56113106]]
Pesos: (3, 1)
Bias: (1,)
