In [7]:
import torch
import numpy as np
# --- Crear tensores ---
t_zeros = torch.zeros(3, 4) # tensor de ceros 3x4
t_rand = torch.rand(2, 3) # valores aleatorios uniformes [0,1)
t_manual = torch.tensor([[1.0, 2.0], [3.0, 4.0]]) # desde lista Python
print("Shape:", t_rand.shape) # torch.Size([2, 3])
print("dtype:", t_rand.dtype) # torch.float32
print("device:", t_rand.device) # cpu
# --- Operaciones elementales ---
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
print(a + b) # tensor([5., 7., 9.])
print(a * b) # multiplicación elemento a elemento
print(torch.dot(a, b)) # producto punto: 1*4 + 2*5 + 3*6 = 32
# --- Interoperabilidad con NumPy ---
np_arr = np.array([1.0, 2.0, 3.0])
t_from_np = torch.from_numpy(np_arr) # comparten memoria
np_from_t = t_manual.numpy() # de vuelta a numpy

Shape: torch.Size([2, 3])
dtype: torch.float32
device: cpu
tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor(32.)


In [9]:
# requires_grad=True le dice a PyTorch que queremos calcular gradientes
x = torch.tensor(2.0, requires_grad=True)
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)
# Función: y = w*x + b (una neurona sin activación)
y = w * x + b
print("y =", y.item()) # 7.0
# Calcular gradientes respecto a y
y.backward()
# dy/dx = w = 3.0
# dy/dw = x = 2.0
# dy/db = 1.0
print("grad x:", x.grad) # tensor(3.)
print("grad w:", w.grad) # tensor(2.)
print("grad b:", b.grad) # tensor(1.)
# IMPORTANTE: limpiar gradientes antes del siguiente paso
x.grad.zero_()
w.grad.zero_()
b.grad.zero_()

y = 7.0
grad x: tensor(3.)
grad w: tensor(2.)
grad b: tensor(1.)


tensor(0.)

In [10]:
import torch
import torch.nn as nn
# Una capa lineal: 3 entradas → 1 salida
neurona = nn.Linear(in_features=3, out_features=1)
# Ver parámetros inicializados aleatoriamente
print("Pesos:", neurona.weight) # shape: (1, 3)
print("Bias:", neurona.bias) # shape: (1,)
# Forward pass con un batch de 5 ejemplos
x = torch.rand(5, 3) # 5 muestras, 3 features
y_pred = neurona(x)
print("Salida:", y_pred.shape) # torch.Size([5, 1])
print(y_pred)

Pesos: Parameter containing:
tensor([[-0.1851,  0.4790, -0.3217]], requires_grad=True)
Bias: Parameter containing:
tensor([0.2688], requires_grad=True)
Salida: torch.Size([5, 1])
tensor([[ 0.2569],
        [ 0.3731],
        [-0.0418],
        [ 0.3927],
        [-0.0465]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch

# 1. Definimos los puntos x donde queremos evaluar la derivada
# Es CRUCIAL pasar `requires_grad=True` para que PyTorch rastree las operaciones en el grafo
valores_x = [1.0, 2.0, 3.0]

print(f"{'x':<5} | {'Derivada Autograd':<20} | {'Derivada Analítica':<20} | {'¿Coinciden?':<10}")
print("-" * 65)

for val in valores_x:
    # Creamos el tensor para el punto x actual
    x = torch.tensor(val, requires_grad=True)
    
    # 2. Construimos el grafo computacional para f(x) = 2x^2 - 3x + 1
    # PyTorch registra internamente cada operación (potencia, multiplicación, resta, suma)
    y = 2 * (x ** 2) - 3 * x + 1
    
    # 3. Backward pass: Calculamos el gradiente (df/dx)
    y.backward()
    
    # El resultado se almacena en el atributo .grad del tensor x
    derivada_autograd = x.grad.item()
    
    # 4. Cálculo manual usando la derivada analítica f'(x) = 4x - 3
    derivada_analitica = 4 * val - 3
    
    # Verificación
    coinciden = "Sí" if derivada_autograd == derivada_analitica else "No"
    
    print(f"{val:<5} | {derivada_autograd:<20} | {derivada_analitica:<20} | {coinciden:<10}")

x     | Derivada Autograd    | Derivada Analítica   | ¿Coinciden?
-----------------------------------------------------------------
1.0   | 1.0                  | 1.0                  | Sí        
2.0   | 5.0                  | 5.0                  | Sí        
3.0   | 9.0                  | 9.0                  | Sí        
